In [1]:
# 連接 MySQL 資料庫
import pymysql
import pandas as pd

import mysql.connector

conn = mysql.connector.connect(db="iiicars",
                               host="139.162.104.154",
                               user="jimmy",
                               passwd="Chiu!@#$%lin1024"
                               )

used_1 = pd.read_sql_query("SELECT brand,year,engine_displacement,op_type,price,km,cruise_control,hid,cd,vcd,dvd,reversing_rader,reversing_video,satellite_navigation,climate_control,push_start,anti_theft_device,power_chair,power_window,city FROM cars",
                         conn)  #除了cars_id、model、used_new、address、source、url和pic_url沒有抓
used_1.head()

,brand,year,engine_displacement,op_type,price,km,cruise_control,hid,cd,vcd,dvd,reversing_rader,reversing_video,satellite_navigation,climate_control,push_start,anti_theft_device,power_chair,power_window,city
0,BENZ,2013,2000,手自排,129.0,53102,1,1,1,0,1,1,1,1,1,1,0,1,0,台北市
1,HYUNDAI,2008,2200,手自排,36.8,202668,1,0,1,0,0,1,0,0,1,0,0,1,0,台南市
2,PORSCHE,2008,4800,手自排,77.8,149643,1,1,1,0,0,1,0,0,1,0,0,1,0,彰化縣
3,BENZ,2011,2200,自排,89.8,76888,1,1,1,0,0,1,1,1,1,0,0,1,0,桃園市
4,MINI,2019,2000,手自排,159.8,7785,1,0,1,0,0,1,1,0,1,1,0,1,0,高雄市

In [2]:
# 顯示空值列
used_1[used_1.isnull().values==True]

Empty DataFrame
Columns: [brand, year, engine_displacement, op_type, price, km, cruise_control, hid, cd, vcd, dvd, reversing_rader, reversing_video, satellite_navigation, climate_control, push_start, anti_theft_device, power_chair, power_window, city]
Index: []

In [3]:
# 將 price 欄標準化
from sklearn import preprocessing
# 先取出 price 欄
price = pd.DataFrame(used_1['price'])
price_scaled = preprocessing.scale(price)
price_scaled

array([[ 1.42532017],
       [-0.40729333],
       [ 0.40764326],
       ...,
       [-0.32778732],
       [-0.40729333],
       [ 0.7455438 ]])

In [4]:
# 將 price_scaled 放回 used 表格，並且刪除 標準化後值大於 3 的列
price_scaled = pd.DataFrame(price_scaled)
used_1 = pd.concat([used_1, price_scaled],axis=1,join='inner')
used_1 = used_1[used_1[abs(0)]<3]
used_1.drop(columns=[0],axis=1,inplace=True)
used_1

,brand,year,engine_displacement,op_type,price,km,cruise_control,hid,cd,vcd,dvd,reversing_rader,reversing_video,satellite_navigation,climate_control,push_start,anti_theft_device,power_chair,power_window,city
0,BENZ,2013,2000,手自排,129.0,53102,1,1,1,0,1,1,1,1,1,1,0,1,0,台北市
1,HYUNDAI,2008,2200,手自排,36.8,202668,1,0,1,0,0,1,0,0,1,0,0,1,0,台南市
2,PORSCHE,2008,4800,手自排,77.8,149643,1,1,1,0,0,1,0,0,1,0,0,1,0,彰化縣
3,BENZ,2011,2200,自排,89.8,76888,1,1,1,0,0,1,1,1,1,0,0,1,0,桃園市
4,MINI,2019,2000,手自排,159.8,7785,1,0,1,0,0,1,1,0,1,1,0,1,0,高雄市
5,NISSAN,2009,2000,手自排,19.8,63000,1,0,0,0,1,1,0,1,1,1,0,1,0,嘉義縣
6,BMW,2015,1600,手自排,91.3,93100,1,1,1,0,0,1,1,0,1,1,0,1,0,高雄市
7,HONDA,2012,1500,手自排,35.8,117616,1,0,1,0,0,1,0,0,1,0,0,0,0,高雄市
8,BENZ,2015,1600,自排,93.8,40000,1,1,0,0,0,1,1,0,1,1,0,1,0,台南市
9,BENZ,2014,2000,手自排,136.0,62937,1,1,1,0,1,1,1,1,1,1,0,1,0,桃園市
10,MAZDA,2005,2000,手自排,15.8,189876,0,0,1,0,0,1,0,0,0,0,0,0,0,高雄市
11,BMW,2014,2000,手自排,138.8,44993,1,1,1,0,0,1,1,1,1,1,0,1,0,新北市
12,BENZ,2007,3000,手自排,63.8,88278,1,1,1,0,1,0,0,0,1,0,0,1,0,新北市
13,HONDA,2015,1500,手自排,39.8,86097,0,0,1,0,0,1,0,0,1,0,0,0,0,嘉義縣
14,FORD,2004,2300,手自排,12.3,107438,0,0,1,0,0,1,0,0,0,0,0,0,0,高雄市
15,BENZ,2013,1600,手自排,79.3,57602,1,1,1,0,0,1,0,0,0,0,0,0,0,高雄市
16,MITSUBISHI,2014,1800,手自排,39.8,127500,1,0,1,0,1,1,1,1,1,1,0,0,0,嘉義縣
17,JEEP,1994,2500,自排,16.8,166990,0,0,0,0,0,0,0,0,0,0,0,0,0,嘉義縣
18,BMW,2008,2500,手自排,53.8,117866,1,1,1,0,0,1,1,0,1,0,0,1,0,台中市
19,VW,2016,2000,手自排,99.8,23539,1,1,1,0,0,1,1,0,1,1,0,0,0,台北市
20,HONDA,2014,1500,手自排,44.8,28430,1,0,1,0,0,1,1,1,1,0,0,0,0,高雄市
21,MAZDA,2007,2000,自排,22.0,160069,0,0,1,0,0,1,0,0,1,0,0,0,0,台南市
22,BENZ,2015,2000,手自排,129.8,95548,1,1,1,0,1,1,1,1,1,1,0,1,0,台北市
23,BMW,2015,2000,手自排,148.0,36161,1,1,1,0,1,1,1,0,1,1,0,1,0,桃園市
24,HONDA,2017,2400,手自排,75.8,35207,1,1,0,0,0,0,1,1,1,0,0,1,0,高雄市
25,FORD,2019,1500,手自排,68.8,12000,1,1,1,0,0,1,1,1,1,1,0,0,0,高雄市
26,BMW,2013,2000,手自排,108.8,123416,1,0,0,0,0,0,0,0,1,1,0,1,0,新北市
27,MITSUBISHI,2002,2900,手排,28.8,248614,0,0,0,0,0,0,0,0,0,0,0,0,0,嘉義縣
28,TOYOTA,2010,3500,手自排,85.3,136669,1,1,1,0,1,1,1,1,1,1,0,1,0,高雄市
29,BMW,2013,2000,手自排,89.8,80000,1,1,1,0,1,1,1,1,1,1,0,1,0,新北市
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24667,VW,2014,3600,手自排,79.8,26652,1,0,1,0,0,1,0,1,0,0,1,1,1,台南市
24668,VW,2014,1395,手自排,68.8,81160,1,0,1,1,1,1,0,1,1,0,1,1,1,台北市
24669,VW,2014,1598,手自排,36.8,57889,0,0,1,0,0,1,0,0,0,0,0,0,1,台中市
24670,VW,2015,1600,自手排,72.8,41000,0,1,1,0,0,1,1,0,0,0,1,0,1,彰化縣
24671,VW,2015,1600,手自排,39.8,62034,0,0,1,0,1,1,0,0,1,0,1,0,1,花蓮縣
24672,VW,2014,2000,手自排,59.9,80000,1,1,1,0,1,1,0,1,1,1,0,0,0,桃園市
24673,VW,2014,1968,手自排,72.8,60000,1,0,1,1,1,1,0,1,1,0,1,1,1,台中市
24674,VW,2017,2000,手自排,118.0,21000,1,1,1,0,1,1,0,1,1,1,0,0,0,台南市
24675,VW,2015,2000,自手排,93.8,100688,0,0,1,0,0,1,0,0,1,0,1,0,1,高雄市
24676,VW,2015,1000,手自排,39.8,70,0,0,1,1,1,1,1,1,1,0,1,0,1,桃園市
24677,VW,2013,1400,自手排,56.8,62377,1,0,1,0,0,1,0,0,0,0,0,0,0,高雄市
24678,VW,2012,1984,自排,75.8,80000,1,0,1,1,1,1,0,1,1,0,1,1,1,桃園市
24679,VW,2015,1000,手自排,46.0,439,0,0,0,0,0,0,0,0,0,0,0,0,0,新北市
24680,VW,2013,1000,手自排,63.8,11995,0,0,0,0,0,0,0,0,0,0,0,0,0,桃園市
24681,VW,2015,1984,手自排,138.0,40000,1,0,1,0,0,1,0,1,1,0,1,1,1,桃園市
24682,VW,2012,2000,手自排,51.8,115698,1,1,1,1,1,1,1,0,1,0,1,1,1,桃園市
24683,VW,2012,1400,自手排,29.8,88715,0,0,1,1,1,1,1,1,1,0,1,0,1,高雄市
24684,VW,2012,2000,自排,71.8,60726,0,0,1,0,0,1,0,0,0,0,1,0,1,台南市
24685,VW,2012,2000,自排,79.8,50395,0,0,1,1,1,1,1,0,0,0,0,0,1,屏東縣
24686,VW,2011,1800,自手排,36.8,121319,1,0,1,1,1,1,1,1,1,0,1,1,1,彰化縣
24687,VW,2011,2000,手自排,40.0,98771,1,0,1,0,0,1,0,0,0,0,1,0,1,台中市
24688,VW,2011,2000,自排,63.8,124125,1,1,1,1,1,1,1,1,1,0,1,1,1,桃園市
24689,VW,2011,1400,自手排,44.8,104723,1,0,1,0,0,1,0,0,1,0,1,0,1,新竹縣
24690,VW,2012,2000,手自排,65.8,99250,0,0,0,0,0,0,0,0,0,0,0,0,0,桃園市
24691,VW,2001,2500,自排,19.8,180000,0,0,0,0,0,0,0,0,0,0,0,0,0,桃園市
24692,VW,2003,2000,自排,29.8,130,0,0,1,0,1,1,0,0,0,0,1,0,1,桃園市
24693,VW,2011,1600,自手排,40.8,28690,1,0,1,0,0,1,0,0,0,0,1,0,1,高雄市
24694,VW,2011,1600,自手排,40.8,28662,1,0,1,0,0,1,0,0,0,0,1,0,1,高雄市
24695,VW,2011,1400,自手排,36.8,68590,0,0,1,0,0,1,0,0,0,0,1,0,1,桃園市
24696,VW,2018,1000,手自排,94.8,5400,1,1,1,0,0,1,1,0,1,0,1,1,1,台中市

In [5]:
#導出one-hot encoding的encoder
#給測試資料集使用
from sklearn.preprocessing import OneHotEncoder
import joblib
import numpy as np
np_used_1 = np.array(df.drop("price", axis=1))

enc = OneHotEncoder(categories = "auto", handle_unknown = "ignore")
used_1_hotEncoded = enc.fit_transform(np_used_1)
# print(used_1_hotEncoded)
joblib.dump(enc, "linear_encoder.pkl")

['linear_encoder.pkl']

In [6]:
#將brand、op_type及city的欄位做 One Hot Encoding
used_2 = pd.get_dummies(used_1)
used_2

,year,engine_displacement,price,km,cruise_control,hid,cd,vcd,dvd,reversing_rader,...,city_屏東縣,city_彰化縣,city_新北市,city_新竹市,city_新竹縣,city_桃園市,city_花蓮縣,city_苗栗縣,city_雲林縣,city_高雄市
0,2013,2000,129.0,53102,1,1,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2008,2200,36.8,202668,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,2008,4800,77.8,149643,1,1,1,0,0,1,...,0,1,0,0,0,0,0,0,0,0
3,2011,2200,89.8,76888,1,1,1,0,0,1,...,0,0,0,0,0,1,0,0,0,0
4,2019,2000,159.8,7785,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
5,2009,2000,19.8,63000,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
6,2015,1600,91.3,93100,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
7,2012,1500,35.8,117616,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
8,2015,1600,93.8,40000,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9,2014,2000,136.0,62937,1,1,1,0,1,1,...,0,0,0,0,0,1,0,0,0,0
10,2005,2000,15.8,189876,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
11,2014,2000,138.8,44993,1,1,1,0,0,1,...,0,0,1,0,0,0,0,0,0,0
12,2007,3000,63.8,88278,1,1,1,0,1,0,...,0,0,1,0,0,0,0,0,0,0
13,2015,1500,39.8,86097,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
14,2004,2300,12.3,107438,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
15,2013,1600,79.3,57602,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
16,2014,1800,39.8,127500,1,0,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
17,1994,2500,16.8,166990,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,2008,2500,53.8,117866,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
19,2016,2000,99.8,23539,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
20,2014,1500,44.8,28430,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
21,2007,2000,22.0,160069,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
22,2015,2000,129.8,95548,1,1,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
23,2015,2000,148.0,36161,1,1,1,0,1,1,...,0,0,0,0,0,1,0,0,0,0
24,2017,2400,75.8,35207,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,2019,1500,68.8,12000,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
26,2013,2000,108.8,123416,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
27,2002,2900,28.8,248614,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,2010,3500,85.3,136669,1,1,1,0,1,1,...,0,0,0,0,0,0,0,0,0,1
29,2013,2000,89.8,80000,1,1,1,0,1,1,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24667,2014,3600,79.8,26652,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24668,2014,1395,68.8,81160,1,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
24669,2014,1598,36.8,57889,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24670,2015,1600,72.8,41000,0,1,1,0,0,1,...,0,1,0,0,0,0,0,0,0,0
24671,2015,1600,39.8,62034,0,0,1,0,1,1,...,0,0,0,0,0,0,1,0,0,0
24672,2014,2000,59.9,80000,1,1,1,0,1,1,...,0,0,0,0,0,1,0,0,0,0
24673,2014,1968,72.8,60000,1,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
24674,2017,2000,118.0,21000,1,1,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
24675,2015,2000,93.8,100688,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
24676,2015,1000,39.8,70,0,0,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
24677,2013,1400,56.8,62377,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
24678,2012,1984,75.8,80000,1,0,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
24679,2015,1000,46.0,439,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
24680,2013,1000,63.8,11995,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24681,2015,1984,138.0,40000,1,0,1,0,0,1,...,0,0,0,0,0,1,0,0,0,0
24682,2012,2000,51.8,115698,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
24683,2012,1400,29.8,88715,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,1
24684,2012,2000,71.8,60726,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24685,2012,2000,79.8,50395,0,0,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
24686,2011,1800,36.8,121319,1,0,1,1,1,1,...,0,1,0,0,0,0,0,0,0,0
24687,2011,2000,40.0,98771,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24688,2011,2000,63.8,124125,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
24689,2011,1400,44.8,104723,1,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
24690,2012,2000,65.8,99250,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24691,2001,2500,19.8,180000,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24692,2003,2000,29.8,130,0,0,1,0,1,1,...,0,0,0,0,0,1,0,0,0,0
24693,2011,1600,40.8,28690,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
24694,2011,1600,40.8,28662,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
24695,2011,1400,36.8,68590,0,0,1,0,0,1,...,0,0,0,0,0,1,0,0,0,0
24696,2018,1000,94.8,5400,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [7]:
# 顯示空值列
used_2[used_2.isnull().values==True]

Empty DataFrame
Columns: [year, engine_displacement, price, km, cruise_control, hid, cd, vcd, dvd, reversing_rader, reversing_video, satellite_navigation, climate_control, push_start, anti_theft_device, power_chair, power_window, brand_ABARTH, brand_AUDI, brand_BENTLEY, brand_BENZ, brand_BMW, brand_CADILLAC, brand_CHEVROLET, brand_CMC, brand_DAIHATSU, brand_FIAT, brand_FORD, brand_HINO, brand_HONDA, brand_HUMMER, brand_HYUNDAI, brand_INFINITI, brand_ISUZU, brand_JAGUAR, brand_JEEP, brand_KIA, brand_LANDROVER, brand_LEXUS, brand_LUXGEN, brand_MASERATI, brand_MAZDA, brand_MINI, brand_MITSUBISHI, brand_NISSAN, brand_PEUGEOT, brand_PORSCHE, brand_PROTON, brand_SAAB, brand_SKODA, brand_SMART, brand_SUBARU, brand_SUZUKI, brand_TOYOTA, brand_VOLKSWAGEN, brand_VOLVO, brand_VW, op_type_手排, op_type_手自排, op_type_自手排, op_type_自排, city_南投縣, city_台中市, city_台北市, city_台南市, city_台東縣, city_嘉義市, city_嘉義縣, city_基隆市, city_宜蘭縣, city_屏東縣, city_彰化縣, city_新北市, city_新竹市, city_新竹縣, city_桃園市, city_花蓮縣, city_苗栗縣, city_雲林縣, city_高雄市]
Index: []

[0 rows x 80 columns]

In [8]:
%matplotlib inline       
import matplotlib.pyplot as plt       
import seaborn as sns; sns.set()       
import numpy as np

# 區分自變數與應變數，將所有X變數放進去跑
x = used_2.drop("price", axis=1)
y = used_2['price']

(24251, 79)

In [14]:
#將數據分成訓練跟測試
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.4, random_state =123) #random_state為隨機種子

In [15]:
#初始化線性回歸模型，並對線性回歸模型進行訓練
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

#copy_X : 布林值,可選,默認是True.如果爲真，則複製X;否則，它可能被覆蓋
#fit_intercept : 布林值,可選.是否計算模型的截距.要是設置為False的話,就不會計算截距了
#n_jobs : 指定訓練時的佔用的資源，設為-1時，則佔用所有的CPU資源
#normalize : 當fit_intercept設置爲False時，將忽略該參數。若爲真，則迴歸前對迴歸量X進行歸一化處理，取均值減去後除以l2-範數。

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
#儲存model檔案
import joblib

joblib.dump(regressor, open("linear_model.pickle", "wb"))

In [30]:
#預測測試結果
y_pred = regressor.predict(x_test)
y_pred

array([ 53.1864453 ,  49.86211295,  28.02942105, ..., 105.18661395,
        43.23804934,  79.08697193])

In [31]:
#模型的斜率(輸出模型的斜率，各項次的係數)
#regressor.coef_

In [32]:
#模型截距(輸出模型的截距（與x=0，y軸的交點)
#regressor.intercept_'''

In [33]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7418998924923286

In [34]:
print('模型得分: %.2f' % regressor.score(x_test, y_test))

模型得分: 0.74

In [35]:
#pearson : 皮爾森相關係數
#約=1 完全相關 (Perfect correlated)
#0.7~0.99 高度相關 (Highly correlated)
#0.4~0.69 中度相關 (Moderately correlated)
#0.1~0.39 低度相關 (Modestly correlated)
#0.01~0.09 接近無相關 (Weakly correlated)
#約=0 無相關
#kendall：用於反映分類變數相關性的指標，即針對無序序列的相關係數，非正太分佈的資料
#spearman：非線性的，非正太分析的資料的相關係數
cor = used_1.corr(method='pearson')
#Correlation with output variable
cor_price = abs(cor["price"])
#Selecting highly correlated features
relevant_features = cor_price[cor_price>0.1]
relevant_features.sort_values(ascending=False)

price                   1.000000
year                    0.535858
power_chair             0.404331
cruise_control          0.392337
push_start              0.321097
hid                     0.285197
reversing_video         0.253271
climate_control         0.247691
satellite_navigation    0.220039
dvd                     0.180497
vcd                     0.145303
Name: price, dtype: float64

In [36]:
'''從皮爾森相關係數得知有中度相關影響二手車車價的條件分別是年份(year)和電動座椅(power chair)，而有低度相關影響車價的分別有
定速(cruise control)和免鑰匙啟動(push start)。'''
#另外車子的品牌(brand)和車子的所在地(city)也會影響車價
used_3 = used_1[['year', 'power_chair', 'cruise_control', 'push_start','brand','city','price']]
used_3

       year  power_chair  cruise_control  push_start       brand city  price
0      2013            1               1           1        BENZ  台北市  129.0
1      2008            1               1           0     HYUNDAI  台南市   36.8
2      2008            1               1           0     PORSCHE  彰化縣   77.8
3      2011            1               1           0        BENZ  桃園市   89.8
4      2019            1               1           1        MINI  高雄市  159.8
5      2009            1               1           1      NISSAN  嘉義縣   19.8
6      2015            1               1           1         BMW  高雄市   91.3
7      2012            0               1           0       HONDA  高雄市   35.8
8      2015            1               1           1        BENZ  台南市   93.8
9      2014            1               1           1        BENZ  桃園市  136.0
10     2005            0               0           0       MAZDA  高雄市   15.8
11     2014            1               1           1         BMW  新北市  138.8
12     2007            1               1           0        BENZ  新北市   63.8
13     2015            0               0           0       HONDA  嘉義縣   39.8
14     2004            0               0           0        FORD  高雄市   12.3
15     2013            0               1           0        BENZ  高雄市   79.3
16     2014            0               1           1  MITSUBISHI  嘉義縣   39.8
17     1994            0               0           0        JEEP  嘉義縣   16.8
18     2008            1               1           0         BMW  台中市   53.8
19     2016            0               1           1          VW  台北市   99.8
20     2014            0               1           0       HONDA  高雄市   44.8
21     2007            0               0           0       MAZDA  台南市   22.0
22     2015            1               1           1        BENZ  台北市  129.8
23     2015            1               1           1         BMW  桃園市  148.0
24     2017            1               1           0       HONDA  高雄市   75.8
25     2019            0               1           1        FORD  高雄市   68.8
26     2013            1               1           1         BMW  新北市  108.8
27     2002            0               0           0  MITSUBISHI  嘉義縣   28.8
28     2010            1               1           1      TOYOTA  高雄市   85.3
29     2013            1               1           1         BMW  新北市   89.8
...     ...          ...             ...         ...         ...  ...    ...
24667  2014            1               1           0          VW  台南市   79.8
24668  2014            1               1           0          VW  台北市   68.8
24669  2014            0               0           0          VW  台中市   36.8
24670  2015            0               0           0          VW  彰化縣   72.8
24671  2015            0               0           0          VW  花蓮縣   39.8
24672  2014            0               1           1          VW  桃園市   59.9
24673  2014            1               1           0          VW  台中市   72.8
24674  2017            0               1           1          VW  台南市  118.0
24675  2015            0               0           0          VW  高雄市   93.8
24676  2015            0               0           0          VW  桃園市   39.8
24677  2013            0               1           0          VW  高雄市   56.8
24678  2012            1               1           0          VW  桃園市   75.8
24679  2015            0               0           0          VW  新北市   46.0
24680  2013            0               0           0          VW  桃園市   63.8
24681  2015            1               1           0          VW  桃園市  138.0
24682  2012            1               1           0          VW  桃園市   51.8
24683  2012            0               0           0          VW  高雄市   29.8
24684  2012            0               0           0          VW  台南市   71.8
24685  2012            0               0           0          VW  屏東縣   79.8
24686  2011            1               1           0          VW  彰化縣   36.8
24687  2011            0               1           0          VW  台中市   40.0
24688  2011            1               1           0          VW  桃園市   63.8
24689  2011            0               1           0          VW  新竹縣   44.8
24690  2012            0               0           0          VW  桃園市   65.8
24691  2001            0               0           0          VW  桃園市   19.8
24692  2003            0               0           0          VW  桃園市   29.8
24693  2011            0               1           0          VW  高雄市   40.8
24694  2011            0               1           0          VW  高雄市   40.8
24695  2011            0               0           0          VW  桃園市   36.8
24696  2018            1               1           0          VW  台中市   94.8

[24251 rows x 7 columns]

In [37]:
#將電動座椅(power chair)、定速(cruise control)和免鑰匙啟動(push start)的欄位做 One Hot Encoding
used_3 = pd.get_dummies(used_3)
used_3

,year,power_chair,cruise_control,push_start,price,brand_ABARTH,brand_AUDI,brand_BENTLEY,brand_BENZ,brand_BMW,...,city_屏東縣,city_彰化縣,city_新北市,city_新竹市,city_新竹縣,city_桃園市,city_花蓮縣,city_苗栗縣,city_雲林縣,city_高雄市
0,2013,1,1,1,129.0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2008,1,1,0,36.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2008,1,1,0,77.8,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,2011,1,1,0,89.8,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
4,2019,1,1,1,159.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,2009,1,1,1,19.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,2015,1,1,1,91.3,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
7,2012,0,1,0,35.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8,2015,1,1,1,93.8,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9,2014,1,1,1,136.0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
10,2005,0,0,0,15.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
11,2014,1,1,1,138.8,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
12,2007,1,1,0,63.8,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
13,2015,0,0,0,39.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,2004,0,0,0,12.3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
15,2013,0,1,0,79.3,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
16,2014,0,1,1,39.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,1994,0,0,0,16.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,2008,1,1,0,53.8,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
19,2016,0,1,1,99.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,2014,0,1,0,44.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
21,2007,0,0,0,22.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,2015,1,1,1,129.8,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
23,2015,1,1,1,148.0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
24,2017,1,1,0,75.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,2019,0,1,1,68.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
26,2013,1,1,1,108.8,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
27,2002,0,0,0,28.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,2010,1,1,1,85.3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
29,2013,1,1,1,89.8,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24667,2014,1,1,0,79.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24668,2014,1,1,0,68.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24669,2014,0,0,0,36.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24670,2015,0,0,0,72.8,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
24671,2015,0,0,0,39.8,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
24672,2014,0,1,1,59.9,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24673,2014,1,1,0,72.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24674,2017,0,1,1,118.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24675,2015,0,0,0,93.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24676,2015,0,0,0,39.8,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24677,2013,0,1,0,56.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24678,2012,1,1,0,75.8,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24679,2015,0,0,0,46.0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
24680,2013,0,0,0,63.8,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24681,2015,1,1,0,138.0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24682,2012,1,1,0,51.8,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24683,2012,0,0,0,29.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24684,2012,0,0,0,71.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24685,2012,0,0,0,79.8,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
24686,2011,1,1,0,36.8,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
24687,2011,0,1,0,40.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24688,2011,1,1,0,63.8,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24689,2011,0,1,0,44.8,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
24690,2012,0,0,0,65.8,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24691,2001,0,0,0,19.8,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24692,2003,0,0,0,29.8,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24693,2011,0,1,0,40.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24694,2011,0,1,0,40.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24695,2011,0,0,0,36.8,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24696,2018,1,1,0,94.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
%matplotlib inline       
import matplotlib.pyplot as plt       
import seaborn as sns; sns.set()       
import numpy as np

# 區分自變數與應變數
x = used_3.drop("price", axis=1)
y = used_3['price']

In [39]:
#將數據分成訓練跟測試
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.4, random_state =123) #random_state為隨機種子

In [40]:
#初始化線性回歸模型，並對線性回歸模型進行訓練
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

#copy_X : 布林值,可選,默認是True.如果爲真，則複製X;否則，它可能被覆蓋
#fit_intercept : 布林值,可選.是否計算模型的截距.要是設置為False的話,就不會計算截距了
#n_jobs : 指定訓練時的佔用的資源，設為-1時，則佔用所有的CPU資源
#normalize : 當fit_intercept設置爲False時，將忽略該參數。若爲真，則迴歸前對迴歸量X進行歸一化處理，取均值減去後除以l2-範數。

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
import pickle
pickle.dump(regressor, open("linear_model.pickle", "wb"))

In [42]:
#預測測試結果
y_pred = regressor.predict(x_test)
y_pred

array([ 55.3373039 ,  46.3716352 ,  27.8536056 , ..., 104.07988046,
        45.42785799,  76.92133219])

In [43]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7326357131867738

In [44]:
print('模型得分: %.2f' % regressor.score(x_test, y_test))

模型得分: 0.73

In [45]:
# 選取這次要測試的欄位，以下為只放全部數值型變數
used_4 = used_1[['year','engine_displacement','price','km','cruise_control','hid','cd','vcd','dvd','reversing_rader','reversing_video','satellite_navigation','climate_control','push_start','anti_theft_device','power_chair','power_window']]
used_4

,year,engine_displacement,price,km,cruise_control,hid,cd,vcd,dvd,reversing_rader,reversing_video,satellite_navigation,climate_control,push_start,anti_theft_device,power_chair,power_window
0,2013,2000,129.0,53102,1,1,1,0,1,1,1,1,1,1,0,1,0
1,2008,2200,36.8,202668,1,0,1,0,0,1,0,0,1,0,0,1,0
2,2008,4800,77.8,149643,1,1,1,0,0,1,0,0,1,0,0,1,0
3,2011,2200,89.8,76888,1,1,1,0,0,1,1,1,1,0,0,1,0
4,2019,2000,159.8,7785,1,0,1,0,0,1,1,0,1,1,0,1,0
5,2009,2000,19.8,63000,1,0,0,0,1,1,0,1,1,1,0,1,0
6,2015,1600,91.3,93100,1,1,1,0,0,1,1,0,1,1,0,1,0
7,2012,1500,35.8,117616,1,0,1,0,0,1,0,0,1,0,0,0,0
8,2015,1600,93.8,40000,1,1,0,0,0,1,1,0,1,1,0,1,0
9,2014,2000,136.0,62937,1,1,1,0,1,1,1,1,1,1,0,1,0
10,2005,2000,15.8,189876,0,0,1,0,0,1,0,0,0,0,0,0,0
11,2014,2000,138.8,44993,1,1,1,0,0,1,1,1,1,1,0,1,0
12,2007,3000,63.8,88278,1,1,1,0,1,0,0,0,1,0,0,1,0
13,2015,1500,39.8,86097,0,0,1,0,0,1,0,0,1,0,0,0,0
14,2004,2300,12.3,107438,0,0,1,0,0,1,0,0,0,0,0,0,0
15,2013,1600,79.3,57602,1,1,1,0,0,1,0,0,0,0,0,0,0
16,2014,1800,39.8,127500,1,0,1,0,1,1,1,1,1,1,0,0,0
17,1994,2500,16.8,166990,0,0,0,0,0,0,0,0,0,0,0,0,0
18,2008,2500,53.8,117866,1,1,1,0,0,1,1,0,1,0,0,1,0
19,2016,2000,99.8,23539,1,1,1,0,0,1,1,0,1,1,0,0,0
20,2014,1500,44.8,28430,1,0,1,0,0,1,1,1,1,0,0,0,0
21,2007,2000,22.0,160069,0,0,1,0,0,1,0,0,1,0,0,0,0
22,2015,2000,129.8,95548,1,1,1,0,1,1,1,1,1,1,0,1,0
23,2015,2000,148.0,36161,1,1,1,0,1,1,1,0,1,1,0,1,0
24,2017,2400,75.8,35207,1,1,0,0,0,0,1,1,1,0,0,1,0
25,2019,1500,68.8,12000,1,1,1,0,0,1,1,1,1,1,0,0,0
26,2013,2000,108.8,123416,1,0,0,0,0,0,0,0,1,1,0,1,0
27,2002,2900,28.8,248614,0,0,0,0,0,0,0,0,0,0,0,0,0
28,2010,3500,85.3,136669,1,1,1,0,1,1,1,1,1,1,0,1,0
29,2013,2000,89.8,80000,1,1,1,0,1,1,1,1,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24667,2014,3600,79.8,26652,1,0,1,0,0,1,0,1,0,0,1,1,1
24668,2014,1395,68.8,81160,1,0,1,1,1,1,0,1,1,0,1,1,1
24669,2014,1598,36.8,57889,0,0,1,0,0,1,0,0,0,0,0,0,1
24670,2015,1600,72.8,41000,0,1,1,0,0,1,1,0,0,0,1,0,1
24671,2015,1600,39.8,62034,0,0,1,0,1,1,0,0,1,0,1,0,1
24672,2014,2000,59.9,80000,1,1,1,0,1,1,0,1,1,1,0,0,0
24673,2014,1968,72.8,60000,1,0,1,1,1,1,0,1,1,0,1,1,1
24674,2017,2000,118.0,21000,1,1,1,0,1,1,0,1,1,1,0,0,0
24675,2015,2000,93.8,100688,0,0,1,0,0,1,0,0,1,0,1,0,1
24676,2015,1000,39.8,70,0,0,1,1,1,1,1,1,1,0,1,0,1
24677,2013,1400,56.8,62377,1,0,1,0,0,1,0,0,0,0,0,0,0
24678,2012,1984,75.8,80000,1,0,1,1,1,1,0,1,1,0,1,1,1
24679,2015,1000,46.0,439,0,0,0,0,0,0,0,0,0,0,0,0,0
24680,2013,1000,63.8,11995,0,0,0,0,0,0,0,0,0,0,0,0,0
24681,2015,1984,138.0,40000,1,0,1,0,0,1,0,1,1,0,1,1,1
24682,2012,2000,51.8,115698,1,1,1,1,1,1,1,0,1,0,1,1,1
24683,2012,1400,29.8,88715,0,0,1,1,1,1,1,1,1,0,1,0,1
24684,2012,2000,71.8,60726,0,0,1,0,0,1,0,0,0,0,1,0,1
24685,2012,2000,79.8,50395,0,0,1,1,1,1,1,0,0,0,0,0,1
24686,2011,1800,36.8,121319,1,0,1,1,1,1,1,1,1,0,1,1,1
24687,2011,2000,40.0,98771,1,0,1,0,0,1,0,0,0,0,1,0,1
24688,2011,2000,63.8,124125,1,1,1,1,1,1,1,1,1,0,1,1,1
24689,2011,1400,44.8,104723,1,0,1,0,0,1,0,0,1,0,1,0,1
24690,2012,2000,65.8,99250,0,0,0,0,0,0,0,0,0,0,0,0,0
24691,2001,2500,19.8,180000,0,0,0,0,0,0,0,0,0,0,0,0,0
24692,2003,2000,29.8,130,0,0,1,0,1,1,0,0,0,0,1,0,1
24693,2011,1600,40.8,28690,1,0,1,0,0,1,0,0,0,0,1,0,1
24694,2011,1600,40.8,28662,1,0,1,0,0,1,0,0,0,0,1,0,1
24695,2011,1400,36.8,68590,0,0,1,0,0,1,0,0,0,0,1,0,1
24696,2018,1000,94.8,5400,1,1,1,0,0,1,1,0,1,0,1,1,1

In [46]:
%matplotlib inline       
import matplotlib.pyplot as plt       
import seaborn as sns; sns.set()       
import numpy as np

# 區分自變數與應變數
x = used_4.drop("price", axis=1)
y = used_4['price']

In [47]:
#將數據分成訓練跟測試
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.4, random_state =123) #random_state為隨機種子

In [48]:
#初始化線性回歸模型，並對線性回歸模型進行訓練
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

#copy_X : 布林值,可選,默認是True.如果爲真，則複製X;否則，它可能被覆蓋
#fit_intercept : 布林值,可選.是否計算模型的截距.要是設置為False的話,就不會計算截距了
#n_jobs : 指定訓練時的佔用的資源，設為-1時，則佔用所有的CPU資源
#normalize : 當fit_intercept設置爲False時，將忽略該參數。若爲真，則迴歸前對迴歸量X進行歸一化處理，取均值減去後除以l2-範數。

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [49]:
#預測測試結果
y_pred = regressor.predict(x_test)
y_pred

array([ 59.01432459,  70.18690626,  32.72662593, ...,  62.1536806 ,
        41.93279095, 105.69238619])

In [50]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.48136195668547277

In [51]:
print('模型得分: %.2f' % regressor.score(x_test, y_test))

模型得分: 0.48

In [52]:
# 關閉連線
conn.close()